public class Calc {
    integer a=10;
    integer b=10;
    integer res;
    
    public void doSum1(){
        res=a+b;
        system.debug('Result=' +res);
        
    }
    
    public void doSub1(){
        res=a-b;
        system.debug('Result=' +res);
        
    }
    public void doMul1(){
        res=a*b;
        system.debug('Result=' +res);
        
    }

    
    public void doDiv1(){
        res=a/b;
        system.debug('Result=' +res);
        
    }


}